### ISSUE TITLE
与鼠标手势类插件冲突

### ISSUE THREAD

**Issue by CocoMilkMaster** [xcanwin/Unlimit-Web#2]
smartup/得力等手势插件使用鼠标右键操作，画手势中临时屏蔽了右键，当前插件会反复解锁右键菜单，使用手势右键菜单就弹出，导致鼠标手势失效。

**Comment by xcanwin** [comment]
> smartup/得力等手势插件使用鼠标右键操作，画手势中临时屏蔽了右键，当前插件会反复解锁右键菜单，使用手势右键菜单就弹出，导致鼠标手势失效。

本次兼容性问题主要是smartup对右键的自定义导致Unlimit-Web误以为是网站对右键的限制。刚刚已兼容手势类插件，如果还是有问题的话，可以把smartup设置成中键触发。
